<?php
$lang_zh_CN=array(
    'WALLET_BALANCE_NOT_ENOUGH' => '钱包余额不足',
    'WALLET_USER_TRANSER_ERR'   => '钱包转账有误',
    'WALLET_WITHDRAW_EXISTS'    => '钱包提现已存在，请等待上次完成后重新操作',
    
    'task_pay_desc'             => '任务#%s的奖励',
    'TASK_PAY'                  => '奖励',
    'withdraw_desc'             => '提现%s',
    'WITHDRAW'                  => '提现',
    'withdraw'                  => '提现',
    'RECHARGE'                  => '充值',
    'recharge_desc'             => '充值',
    
    'APPLIED'                   => '已申请',
    'ACCEPTED'                  => '已受理',
    'FAILED'                    => '失败',
    'SUCCEEDED'                 => '成功',
    'apply'                     => '申请',
    
    'balance'                   => '余额',
    'money'                     => '资金',
    'total'                     => '总计',
    'transaction'               => '交易',
    'account'                   => '帐号',
    'quantity'                  => '笔数',
    
    'do_oper'                   => '待处理',
    'done_oper'                 => '已处理',
    'withdraw_stat_desc'        => '前<b>%d</b>条，剩余<b>%d</b>条',   
    'batch_withdraw'            => '批量处理提现',
    'batch_select_desc'         => '已选<i class=red>%d</i>笔提现申请，总金额<i class=red>￥%d</i>，平均每笔<i class=red>￥%d</i>,',
    'sys_refuse_reason'         => array(
        '金额太大',
        '帐号异常',
        '操作频繁',
        '其他'
    ),
    'refuse_notice'             => '请选择拒绝原因',
    'bat_no'                    => '批次号',
    'amount'                    => '金额',
    'success'                   => '成功',
    'fault'                     => '失败',
    'response'                  => '响应',
    'detail'                    => '详情',
    
    'alierr'                    =>array(
        'ERROR_USER_ID_NULL'=>'用户名为空',
        'ERROR_USER_INFO_NULL'=>'用户信息为空',
        'ERROR_BALANCE_NULL'=>'用户余额不存在',
        'PAYER_ACCOUNT_IS_RELEASED'=>'付款账户名与他人重复，无法进行收付款',
        'PAYER_USERINFO_NOT_EXIST'=>'抱歉，您上传文件中的付款账户，与其所对应的账户信息不匹配或状态异常',
        'RECEIVE_EMAIL_ERROR'=>'收款人EMAIL的长度不正确，不能为空或必须小于等于100个字符',
        'RECEIVE_NAME_ERROR'=>'收款人姓名的长度不正确，不能为空或必须小于等于128个字符',
        'RECEIVE_ACCOUNT_ERROR'=>'收款账户有误或不存在',
        'RECEIVE_SINGLE_MONEY_ERROR'=>'收款金额超限',
        'TRANSFER_AMOUNT_NOT_ENOUGH'=>'转账余额不足，批次失败',
        'RECEIVE_USER_NOT_EXIST'=>'收款用户不存在',
        'ILLEGAL_USER_STATUS'=>'用户状态不正确',
        'ACCOUN_NAME_NOT_MATCH'=>'用户姓名和收款名称不匹配',
        'ERROR_OTHER_CERTIFY_LEVEL_LIMIT'=>'收款账户实名认证信息不完整，无法收款',
        'ERROR_OTHER_NOT_REALNAMED'=>'收款账户尚未实名认证，无法收款',
        'USER_NOT_EXIST'=>'用户不存在',
        'PERMIT_NON_BANK_LIMIT_PAYEE_L0_FORBIDDEN'=>'根据监管部门的要求，对方未完善身份信息，无法收款',
        'PERMIT_PAYER_L1_FORBIDDEN'=>'根据监管部门的要求，当前余额支付额度仅剩XX元，请尽快完善身份信息提升额度',
        'PERMIT_PAYER_L2_L3_FORBIDDEN'=>'根据监管部门的要求，您今日余额支付额度仅剩XX元，今年余额支付额度仅剩XX元',
        'PERMIT_CHECK_PERM_AML_CERT_MISS_4_TRANS_LIMIT'=>'您的账户收付款额度超限',
        'PERMIT_CHECK_PERM_AML_CERT_MISS_4_ACC_LIMIT'=>'为了保证您的资金安全，请尽快完成信息补全',
        'PERMIT_CHECK_PERM_IDENTITY_THEFT'=>'您的账户存在身份冒用风险，请进行身份核实解除限制',
        'PERMIT_CHECK_PERM_LIMITED_BY_SUPERIOR'=>'根据监管部门的要求，请补全您的身份信息解除限制',
        'PERMIT_CHECK_PERM_ACCOUNT_NOT_EXIST'=>'根据监管部门的要求，请补全您的身份信息，开立余额账户',
        'PERMIT_CHECK_PERM_INSUFFICIENT_ACC_LEVEL'=>'根据监管部门的要求，请完善身份信息解除限制',
    ),
    
    'I_have_been_payed'  => '已完成支付',
    'some_wrongs_happened' => '发生错误',
    'popwin_select_res_notice' => '开始于%s的批次(%d)由于某种原因没有结果，请选择',
);
?>